Added SLFO images, moved "jq" test

diff --git a/live-iso/download/agama-image-dirs b/live-iso/download/agama-image-dirs
--- a/live-iso/download/agama-image-dirs
+++ b/live-iso/download/agama-image-dirs
@@ -13,6 +13,11 @@ if [ "$OUT_DIR" == "-h" ] || [ "$OUT_DIR" == "--help" ]; then
   exit 0
 fi
 
+if ! command -v jq >/dev/null; then
+  echo "Error: The required 'jq' tool is not installed."
+  exit 1
+fi
+
 if command -v agama-download-image >/dev/null; then
   DOWNLOAD_SCRIPT="agama-download-image"
 else
@@ -64,18 +69,15 @@ create_scripts "systemsmanagement:Agama:Devel" "devel-tw" "devel-leap" "download
 if curl --head --silent --fail --connect-timeout 5 --max-time 5 -L "https://download.suse.de" >/dev/null; then
   create_scripts "sles-16.0-GM" "sles-16.0-online" "sles-16.0-offline" "" ""
   create_scripts "sles-16.0-QU-next" "sles-16.0-QU-next-online" "sles-16.0-QU-next-offline" "" ""
-  create_scripts "sles-16.1-SLFO" "devel-sles-test-online" "devel-sles-test-offline" "" ""
+  create_scripts "sles-16.1-SLFO-Test" "devel-sles-slfo-test-online" "devel-sles-slfo-test-offline" "" ""
+  create_scripts "sles-16.1-SLFO" "devel-sles-slfo-online" "devel-sles-slfo-offline" "" ""
   create_scripts "sles-16.1-Beta" "sles-16.1-beta-online" "sles-16.1-beta-offline" "" ""
   create_scripts "Devel:YaST:Agama:Head" "devel-sles" "" "" ""
   # Dynamically obtain the list of QU images
-  if command -v jq >/dev/null; then
-    BASE_URL="https://download.suse.de/ibs/SUSE:/SLFO:/Products:/SLES:/16.0:"
-    for QU in $(curl -L -s "${BASE_URL}/?jsontable" | jq -r ".data[] | select(.name|test(\"^QU[0-9]+/\$\")) | .name" | tr -d "/"); do
-      create_scripts "sles-16.0-${QU}" "sles-16.0-${QU}-online" "sles-16.0-${QU}-offline" "" ""
-    done
-  else
-    echo "Warning: \"jq\" not found, skipping QU images."
-  fi
+	BASE_URL="https://download.suse.de/ibs/SUSE:/SLFO:/Products:/SLES:/16.0:"
+	for QU in $(curl -L -s "${BASE_URL}/?jsontable" | jq -r ".data[] | select(.name|test(\"^QU[0-9]+/\$\")) | .name" | tr -d "/"); do
+		create_scripts "sles-16.0-${QU}" "sles-16.0-${QU}-online" "sles-16.0-${QU}-offline" "" ""
+	done
 else
   echo "Warning: https://download.suse.de is not accessible, skipping internal SLES images."
 fi
