Added sles-16.0-QU-next, download sha512 checksum if sha256 fails

diff --git a/live-iso/download/agama-download-image b/live-iso/download/agama-download-image
--- a/live-iso/download/agama-download-image
+++ b/live-iso/download/agama-download-image
@@ -32,7 +32,7 @@ fi
 # Check for terminal hyperlink support
 HYPERLINKS=false
 if [[ -t 1 ]]; then
-  # can some other terminals display links?
+  # TODO: can some other terminals display links?
   if [ "${VTE_VERSION:-0}" -ge 5000 ] ||
     [ "${TERM_PROGRAM:-}" = "vscode" ]; then
     HYPERLINKS=true
@@ -150,6 +150,21 @@ function print_released_images() {
 function print_testing_images() {
   echo "Testing images:"
   echo "==============="
+  echo
+  echo "  SLES 16.0 - Next QU"
+  echo "  -------------------"
+  echo
+  printf "  ID: "
+  green "sles-16.0-QU-next-offline"
+  echo "  Description: Testing image for the next SLES 16.0 quarterly update (Offline)"
+  print_image "https://download.suse.de/ibs/SUSE:/SLFO:/Products:/SLES:/16.0:/TEST/product/iso/" \
+    "SLES-16\\\\.0-Full-${ARCH}-.*\\\\.install\\\\.iso\$"
+  echo
+  printf "  ID: "
+  green "sles-16.0-QU-next-online"
+  echo "  Description: Testing image for the next SLES 16.0 quarterly update (Online)"
+  print_image "https://download.suse.de/ibs/SUSE:/SLFO:/Products:/SLES:/16.0:/TEST/product/iso/" \
+    "SLES-16\\\\.0-Online-${ARCH}-.*\\\\.install\\\\.iso\$"
   echo
   echo "  openSUSE Leap 16.1"
   echo "  ------------------"
@@ -329,6 +344,7 @@ function verify_signature_with_keyring() {
 }
 
 function verify_checksum_and_signature() {
+  local HASH_ALGO="sha256"
   if [ -n "$CHECKSUM_DOWNLOAD_URL" ]; then
     CHECKSUM_URL="${CHECKSUM_DOWNLOAD_URL}"
     CHECKSUM_FILE="${CHECKSUM_DOWNLOAD_URL##*/}"
@@ -342,7 +358,21 @@ function verify_checksum_and_signature() {
   fi
 
   echo "Downloading checksum ${CHECKSUM_FILE}..."
-  curl -s -L -O "$CHECKSUM_URL"
+  if ! curl --fail -s -L -O "$CHECKSUM_URL"; then
+    if [ -z "$CHECKSUM_DOWNLOAD_URL" ]; then
+      echo "Downloading .sha256 failed, trying .sha512..."
+      CHECKSUM_URL="${URL}.sha512"
+      CHECKSUM_FILE="${URL##*/}.sha512"
+      GPG_URL="${CHECKSUM_URL}.asc"
+      GPG_FILE="${CHECKSUM_FILE}.asc"
+      HASH_ALGO="sha512"
+      echo "Downloading checksum ${CHECKSUM_FILE}..."
+      curl --fail -s -L -O "$CHECKSUM_URL" || { red "Failed to download checksum"; exit 1; }
+    else
+      red "Failed to download checksum file from $CHECKSUM_URL."
+      exit 1
+    fi
+  fi
 
   # remove the lines from the checksum file which do not match the current image
   sed -i "/${URL##*/}$/!d" "$CHECKSUM_FILE"
@@ -398,11 +428,12 @@ function verify_checksum_and_signature() {
     fi
   fi
 
-  echo "Verifying SHA256 checksum..."
-  if sha256sum --status -c "$CHECKSUM_FILE"; then
-    green "${URL##*/}: SHA256 checksum OK"
+  local HASH_NAME=$(echo "$HASH_ALGO" | tr "[:lower:]" "[:upper:]")
+  echo "Verifying ${HASH_NAME} checksum..."
+  if ${HASH_ALGO}sum --status -c "$CHECKSUM_FILE"; then
+    green "${URL##*/}: ${HASH_NAME} checksum OK"
   else
-    red "${URL##*/}: SHA256 checksum does not match, broken file?"
+    red "${URL##*/}: ${HASH_NAME} checksum does not match, broken file?"
     exit 1
   fi
 }
@@ -458,17 +489,27 @@ case "$IMAGE" in
   CHECKSUM_DOWNLOAD_URL="https://download.suse.de/install/SLES-16-GM/SHA256SUMS"
   ;;
 sles-16.0-QU*-offline | sles-16.0-QU*-online)
-  # get QU number from $IMAGE
-  QU=$(echo "$IMAGE" | sed -E 's/sles-16.0-(QU[0-9]+)-(offline|online)/\1/')
-  TYPE=$(echo "$IMAGE" | sed -E 's/sles-16.0-(QU[0-9]+)-(offline|online)/\2/')
-  BASE_URL="https://download.suse.de/ibs/SUSE:/SLFO:/Products:/SLES:/16.0:/${QU}/product/iso/"
-
-  if [[ "$TYPE" == "offline" ]]; then
+  if [ "$IMAGE" == "sles-16.0-QU-next-offline" ]; then
+    BASE_URL="https://download.suse.de/ibs/SUSE:/SLFO:/Products:/SLES:/16.0:/TEST/product/iso/"
     PATTERN="SLES-16\\\\.0-Full-${ARCH}-.*\\\\.install\\\\.iso\$"
-  else
+    URL="${BASE_URL}$(latest_version "$BASE_URL" "$PATTERN")"
+  elif [ "$IMAGE" == "sles-16.0-QU-next-online" ]; then
+    BASE_URL="https://download.suse.de/ibs/SUSE:/SLFO:/Products:/SLES:/16.0:/TEST/product/iso/"
     PATTERN="SLES-16\\\\.0-Online-${ARCH}-.*\\\\.install\\\\.iso\$"
+    URL="${BASE_URL}$(latest_version "$BASE_URL" "$PATTERN")"
+  else
+    # get QU number from $IMAGE
+    QU=$(echo "$IMAGE" | sed -E 's/sles-16.0-(QU[0-9]+)-(offline|online)/\1/')
+    TYPE=$(echo "$IMAGE" | sed -E 's/sles-16.0-(QU[0-9]+)-(offline|online)/\2/')
+    BASE_URL="https://download.suse.de/ibs/SUSE:/SLFO:/Products:/SLES:/16.0:/${QU}/product/iso/"
+
+    if [[ "$TYPE" == "offline" ]]; then
+      PATTERN="SLES-16\\\\.0-Full-${ARCH}-.*\\\\.install\\\\.iso\$"
+    else
+      PATTERN="SLES-16\\\\.0-Online-${ARCH}-.*\\\\.install\\\\.iso\$"
+    fi
+    URL="${BASE_URL}$(latest_version "$BASE_URL" "$PATTERN")"
   fi
-  URL="${BASE_URL}$(latest_version "$BASE_URL" "$PATTERN")"
   ;;
 "leap-16.1-beta-offline")
   BASE_URL="https://download.opensuse.org/distribution/leap/16.1/offline/"
